<a href="https://colab.research.google.com/github/ChandanaPulikanti/Data-files/blob/main/alcovex_task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Predicting the next occurring word when given a sentence.


In [ ]:
#read the corpus(this is a sample file, upload task specific corpus in corpus text file and proceed)
corpus=open("/content/pg5200.txt").read()

In [ ]:
corpus

'\ufeffThe Project Gutenberg EBook of Metamorphosis, by Franz Kafka\nTranslated by David Wyllie.\n\nThis eBook is for the use of anyone anywhere at no cost and with\nalmost no restrictions whatsoever.  You may copy it, give it away or\nre-use it under the terms of the Project Gutenberg License included\nwith this eBook or online at www.gutenberg.org\n\n** This is a COPYRIGHTED Project Gutenberg eBook, Details Below **\n**     Please follow the copyright guidelines in this file.     **\n\n\nTitle: Metamorphosis\n\nAuthor: Franz Kafka\n\nTranslator: David Wyllie\n\nRelease Date: August 16, 2005 [EBook #5200]\nFirst posted: May 13, 2002\nLast updated: May 20, 2012\n\nLanguage: English\n\n\n*** START OF THIS PROJECT GUTENBERG EBOOK METAMORPHOSIS ***\n\n\n\n\nCopyright (C) 2002 David Wyllie.\n\n\n\n\n\n  Metamorphosis\n  Franz Kafka\n\nTranslated by David Wyllie\n\n\n\nI\n\n\nOne morning, when Gregor Samsa woke from troubled dreams, he found\nhimself transformed in his bed into a horrible v

In [ ]:
#preprocess the corpus
import re
corpus=corpus.lower()
clean_corpus=re.sub('[^a-z0-9]+',' ', corpus)

In [ ]:
clean_corpus

' the project gutenberg ebook of metamorphosis by franz kafka translated by david wyllie this ebook is for the use of anyone anywhere at no cost and with almost no restrictions whatsoever you may copy it give it away or re use it under the terms of the project gutenberg license included with this ebook or online at www gutenberg org this is a copyrighted project gutenberg ebook details below please follow the copyright guidelines in this file title metamorphosis author franz kafka translator david wyllie release date august 16 2005 ebook 5200 first posted may 13 2002 last updated may 20 2012 language english start of this project gutenberg ebook metamorphosis copyright c 2002 david wyllie metamorphosis franz kafka translated by david wyllie i one morning when gregor samsa woke from troubled dreams he found himself transformed in his bed into a horrible vermin he lay on his armour like back and if he lifted his head a little he could see his brown belly slightly domed and divided by arc

In [ ]:
#required libraries
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
import numpy as np

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
#tokenizing the text into words
tokens = word_tokenize(clean_corpus)
tokens

['the',
 'project',
 'gutenberg',
 'ebook',
 'of',
 'metamorphosis',
 'by',
 'franz',
 'kafka',
 'translated',
 'by',
 'david',
 'wyllie',
 'this',
 'ebook',
 'is',
 'for',
 'the',
 'use',
 'of',
 'anyone',
 'anywhere',
 'at',
 'no',
 'cost',
 'and',
 'with',
 'almost',
 'no',
 'restrictions',
 'whatsoever',
 'you',
 'may',
 'copy',
 'it',
 'give',
 'it',
 'away',
 'or',
 're',
 'use',
 'it',
 'under',
 'the',
 'terms',
 'of',
 'the',
 'project',
 'gutenberg',
 'license',
 'included',
 'with',
 'this',
 'ebook',
 'or',
 'online',
 'at',
 'www',
 'gutenberg',
 'org',
 'this',
 'is',
 'a',
 'copyrighted',
 'project',
 'gutenberg',
 'ebook',
 'details',
 'below',
 'please',
 'follow',
 'the',
 'copyright',
 'guidelines',
 'in',
 'this',
 'file',
 'title',
 'metamorphosis',
 'author',
 'franz',
 'kafka',
 'translator',
 'david',
 'wyllie',
 'release',
 'date',
 'august',
 '16',
 '2005',
 'ebook',
 '5200',
 'first',
 'posted',
 'may',
 '13',
 '2002',
 'last',
 'updated',
 'may',
 '20',
 '20

In [ ]:
train_len = 3

In [ ]:
#converting the data into required sequence
text_sequences = []
for i in range(train_len,len(tokens)+1):
  seq = tokens[i-train_len:i]
  text_sequences.append(seq)

In [ ]:
text_sequences

[['the', 'project', 'gutenberg'],
 ['project', 'gutenberg', 'ebook'],
 ['gutenberg', 'ebook', 'of'],
 ['ebook', 'of', 'metamorphosis'],
 ['of', 'metamorphosis', 'by'],
 ['metamorphosis', 'by', 'franz'],
 ['by', 'franz', 'kafka'],
 ['franz', 'kafka', 'translated'],
 ['kafka', 'translated', 'by'],
 ['translated', 'by', 'david'],
 ['by', 'david', 'wyllie'],
 ['david', 'wyllie', 'this'],
 ['wyllie', 'this', 'ebook'],
 ['this', 'ebook', 'is'],
 ['ebook', 'is', 'for'],
 ['is', 'for', 'the'],
 ['for', 'the', 'use'],
 ['the', 'use', 'of'],
 ['use', 'of', 'anyone'],
 ['of', 'anyone', 'anywhere'],
 ['anyone', 'anywhere', 'at'],
 ['anywhere', 'at', 'no'],
 ['at', 'no', 'cost'],
 ['no', 'cost', 'and'],
 ['cost', 'and', 'with'],
 ['and', 'with', 'almost'],
 ['with', 'almost', 'no'],
 ['almost', 'no', 'restrictions'],
 ['no', 'restrictions', 'whatsoever'],
 ['restrictions', 'whatsoever', 'you'],
 ['whatsoever', 'you', 'may'],
 ['you', 'may', 'copy'],
 ['may', 'copy', 'it'],
 ['copy', 'it', 'give'],


In [ ]:
#converting the texts into integer sequence
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)
sequences

[[1, 47, 43],
 [47, 43, 286],
 [43, 286, 5],
 [286, 5, 512],
 [5, 512, 56],
 [512, 56, 680],
 [56, 680, 681],
 [680, 681, 837],
 [681, 837, 56],
 [837, 56, 589],
 [56, 589, 590],
 [589, 590, 28],
 [590, 28, 286],
 [28, 286, 76],
 [286, 76, 19],
 [76, 19, 1],
 [19, 1, 151],
 [1, 151, 5],
 [151, 5, 272],
 [5, 272, 682],
 [272, 682, 23],
 [682, 23, 50],
 [23, 50, 838],
 [50, 838, 3],
 [838, 3, 15],
 [3, 15, 170],
 [15, 170, 50],
 [170, 50, 1091],
 [50, 1091, 839],
 [1091, 839, 31],
 [839, 31, 216],
 [31, 216, 273],
 [216, 273, 9],
 [273, 9, 242],
 [9, 242, 9],
 [242, 9, 103],
 [9, 103, 34],
 [103, 34, 253],
 [34, 253, 151],
 [253, 151, 9],
 [151, 9, 140],
 [9, 140, 1],
 [140, 1, 159],
 [1, 159, 5],
 [159, 5, 1],
 [5, 1, 47],
 [1, 47, 43],
 [47, 43, 227],
 [43, 227, 683],
 [227, 683, 15],
 [683, 15, 28],
 [15, 28, 286],
 [28, 286, 34],
 [286, 34, 684],
 [34, 684, 23],
 [684, 23, 513],
 [23, 513, 43],
 [513, 43, 274],
 [43, 274, 28],
 [274, 28, 76],
 [28, 76, 12],
 [76, 12, 1092],
 [12, 109

In [ ]:
sequences=np.asarray(sequences)

In [ ]:
#vocabulary size
vocabulary_size = len(tokenizer.word_counts)+1
vocabulary_size

3016

In [ ]:
#trainX
train_inputs=sequences[:,:-1]

In [ ]:
train_inputs

array([[  1,  47],
       [ 47,  43],
       [ 43, 286],
       ...,
       [  2, 264],
       [264,  61],
       [ 61, 252]])

In [ ]:
#input sequence length 
seq_length=train_inputs.shape[1]
seq_length

2

In [ ]:
#trainY
train_targets=sequences[:,-1]

In [ ]:
train_targets

array([ 43, 286,   5, ...,  61, 252, 511])

In [ ]:
#one hot encoding
train_targets = to_categorical(train_targets, num_classes=vocabulary_size)

In [ ]:
train_targets

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
#required libraries
import torch
from torch.optim import Adam
import torch.nn as nn

In [ ]:

#lstm model
class lstm(nn.Module):
    def __init__(self, vocab_size, embed_size, hidden_size):
        super().__init__()
        #simple lookup table that stores embeddings of a fixed dictionary and size.
        self.embed = nn.Embedding(vocab_size, embed_size)
        
        #lstm 
        self.lstm = nn.LSTM(embed_size, hidden_size, num_layers=2, bidirectional=False)
        
        #fully connected layer
        self.linear = nn.Linear(hidden_size*seq_length,vocab_size)
    
    def forward(self, input_word):
        #input sequence to embeddings
        embedded = self.embed(input_word)
        
        #passing the embedding to lstm model
        output, hidden = self.lstm(embedded)
        
        #reshaping
        output=output.view(output.size(0), -1)
        
        #fully connected layer
        output = self.linear(output)
        return output,hidden

In [ ]:

model=lstm(vocab_size=vocabulary_size,embed_size=128, hidden_size=256)

In [ ]:

model

lstm(
  (embed): Embedding(3016, 128)
  (lstm): LSTM(128, 256, num_layers=2)
  (linear): Linear(in_features=512, out_features=3016, bias=True)
)

In [ ]:
#Adam optimizer
optimizer= Adam(model.parameters(), lr=0.07)

#loss
criterion = nn.BCEWithLogitsLoss()

In [ ]:
#training the model
def train(epoch):
    #set the model to train
    model.train()
    tr_loss=0    
    
    #clearing the Gradients 
    optimizer.zero_grad()
    
    #predict the output
    y_pred, (state_h, state_c) = model(torch.from_numpy(train_inputs))
    
    #compute the loss
    loss=criterion(y_pred,torch.from_numpy(train_targets))
    losses.append(loss)
    
    #backpropagate
    loss.backward()

    #update the parameters
    optimizer.step()
    tr_loss = loss.item()

    print("Epoch : ",epoch,"loss : ",loss)

In [ ]:
#number of epoch
no_epoch=3
losses = []
for epoch in range(1,no_epoch+1):
    train(epoch)

Epoch :  1 loss :  tensor(0.6939, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  2 loss :  tensor(0.0050, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  3 loss :  tensor(0.0037, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [ ]:
from sklearn.metrics import accuracy_score
def predict_next_word(text):
    #set the model to evaluation
    model.eval()

    #preprocess
    text = text.lower().strip()
    
    #converting the text to word tokens
    input_tokens = word_tokenize(text)
    
    #converting the tokens to integer sequence
    sequences = tokenizer.texts_to_sequences([input_tokens])
    
    #converting to array
    sequences=np.asarray(sequences)
    with torch.no_grad():
        #converting to tensor
        sequences=torch.from_numpy(sequences)
        #predicting the output
        predict,(hidden,cell)=model(sequences)
    
    #applying the softmax layer
    softmax = torch.exp(predict)
    prob = list(softmax.numpy())
    
    #index of the predict word
    predictions = np.argmax(prob)

    #converting the sequence back to word
    next_word=tokenizer.sequences_to_texts([[predictions]])
    return next_word
     


In [ ]:

#trained our model with sequence length of 2
input_text="her knees"

In [ ]:
print("Possible next word will be:")
predict_next_word(input_text)

Possible next word will be:


['and']

In [ ]:
#trained our model with sequence length of 2
input_text="asked that"

In [ ]:
print("Possible next word will be:")
predict_next_word(input_text)

Possible next word will be:


['of']

In [ ]:
#trained our model with sequence length of 2
input_text="modest pleasures"

In [ ]:
print("Possible next word will be:")
predict_next_word(input_text)

Possible next word will be:


['and']